install.packages('gdata')
install.packages('corrgram')
install.packages('stargazer')
install.packages('RGtk2')
install.packages('rattle')
install.packages('randomForest')
install.packages('inTrees')
install.packages('rpart.plot')
install.packages('RColorBrewer')

library(devtools)
install_github("vqv/ggbiplot")
