install.packages("devtools", dependencies=TRUE) 
install.packages("plyr", dependencies=TRUE)
install.packages("ggplot2", dependencies=TRUE)
install.packages("gcookbook", dependencies=TRUE)
install.packages("digest", dependencies=TRUE)
install.packages('gdata', dependencies=TRUE)
install.packages('corrgram', dependencies=TRUE)
install.packages('stargazer', dependencies=TRUE)
install.packages('RGtk2', dependencies=TRUE)
install.packages('rattle', dependencies=TRUE)
install.packages('randomForest', dependencies=TRUE)
install.packages('inTrees', dependencies=TRUE)
install.packages('rpart.plot', dependencies=TRUE)
install.packages('RColorBrewer', dependencies=TRUE)

library(devtools)
install_github("vqv/ggbiplot", dependencies=TRUE)
